//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите товар в корзину:.
        /// </summary>
        internal static string AddItemToCart {
            get {
                return ResourceManager.GetString("AddItemToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма к оплате: .
        /// </summary>
        internal static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина пуста!.
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Генерация специального дня в который будет выдаваться Квантовая скидочная карта
        ///2. Срок действия Квантовой скидочной карты
        ///
        ///Для выхода нажмите клавишу &apos;q&apos;
        ///
        ///Выберите действие: .
        /// </summary>
        internal static string DiscountCardSettingsMenu {
            get {
                return ResourceManager.GetString("DiscountCardSettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите цену товара: .
        /// </summary>
        internal static string EnterPriceProduct {
            get {
                return ResourceManager.GetString("EnterPriceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание товара.
        /// </summary>
        internal static string EnterProductDescription {
            get {
                return ResourceManager.GetString("EnterProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите ID товара: .
        /// </summary>
        internal static string EnterProductID {
            get {
                return ResourceManager.GetString("EnterProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название товара.
        /// </summary>
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество: .
        /// </summary>
        internal static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите количество товара: .
        /// </summary>
        internal static string EnterQuantityProduct {
            get {
                return ResourceManager.GetString("EnterQuantityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для выхода нажмите клавишу &apos;q&apos;.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Здравствуйте .
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы авторизованы.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизуйтесь
        ///Логин: .
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Путь для файла логирования
        ///2. Настройки для дисконтных карт
        ///
        ///Нажмите клавишу &apos;q&apos;, чтобы разлогиниться
        ///
        ///Выберите действие:  .
        /// </summary>
        internal static string MenuForAdmin {
            get {
                return ResourceManager.GetString("MenuForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Выбрать товар
        ///2. Корзина
        ///
        ///Нажмите клавишу &apos;q&apos;, чтобы разлогиниться
        ///
        ///Выберите действие: .
        /// </summary>
        internal static string MenuForBuyer {
            get {
                return ResourceManager.GetString("MenuForBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Добавить товар
        ///2. Удалить товар
        ///3. Редактировать продукт
        ///
        ///Нажмите клавишу &apos;q&apos;, чтобы разлогиниться
        ///
        ///Выберите действие: .
        /// </summary>
        internal static string MenuForSeller {
            get {
                return ResourceManager.GetString("MenuForSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Оплатить товар
        ///2. Изменить количество в каждой позиции
        ///3. Удалить товар из корзины
        ///
        ///Для выхода нажмите клавишу &apos;q&apos;
        ///
        ///Выберите действие: .
        /// </summary>
        internal static string MenuShowCart {
            get {
                return ResourceManager.GetString("MenuShowCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не авторизовались!.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль: .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите полный путь до файла логирования.
        /// </summary>
        internal static string PathToLogFile {
            get {
                return ResourceManager.GetString("PathToLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  рублей.
        /// </summary>
        internal static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерация специального дня в который будет выдаваться Квантовая скидочная карта.
        /// </summary>
        internal static string SpecialDayForQuantumDiscountCard {
            get {
                return ResourceManager.GetString("SpecialDayForQuantumDiscountCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению, оплата не прошла!.
        /// </summary>
        internal static string SuccessfulNotPayment {
            get {
                return ResourceManager.GetString("SuccessfulNotPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплата прошла успешно!.
        /// </summary>
        internal static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для удаления введите ID товара: .
        /// </summary>
        internal static string ToDeleteEnterProductID {
            get {
                return ResourceManager.GetString("ToDeleteEnterProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для редактирования введите ID товара: .
        /// </summary>
        internal static string ToEditEnterProductID {
            get {
                return ResourceManager.GetString("ToEditEnterProductID", resourceCulture);
            }
        }
    }
}
