//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUI.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите товар в корзину:.
        /// </summary>
        internal static string AddItemToCart {
            get {
                return ResourceManager.GetString("AddItemToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма к оплате: .
        /// </summary>
        internal static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корзина пуста!.
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите цену товара: .
        /// </summary>
        internal static string EnterPriceProduct {
            get {
                return ResourceManager.GetString("EnterPriceProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите описание товара.
        /// </summary>
        internal static string EnterProductDescription {
            get {
                return ResourceManager.GetString("EnterProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите ID товара: .
        /// </summary>
        internal static string EnterProductID {
            get {
                return ResourceManager.GetString("EnterProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название товара.
        /// </summary>
        internal static string EnterProductName {
            get {
                return ResourceManager.GetString("EnterProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество: .
        /// </summary>
        internal static string EnterQuantity {
            get {
                return ResourceManager.GetString("EnterQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите количество товара: .
        /// </summary>
        internal static string EnterQuantityProduct {
            get {
                return ResourceManager.GetString("EnterQuantityProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выхода нажмите клавишу &apos;q&apos;.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Здравствуйте .
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы авторизованы.
        /// </summary>
        internal static string LoggedIn {
            get {
                return ResourceManager.GetString("LoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторизуйтесь
        ///Логин: .
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Выбрать товар
        ///2. Корзина
        ///
        ///Нажмите клавишу &apos;q&apos;, чтобы разлогиниться
        ///.
        /// </summary>
        internal static string MenuForBuyer {
            get {
                return ResourceManager.GetString("MenuForBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Добавить товар
        ///2. Удалить товар
        ///3. Редактировать продукт
        ///
        ///Нажмите клавишу &apos;q&apos;, чтобы разлогиниться.
        /// </summary>
        internal static string MenuForSeller {
            get {
                return ResourceManager.GetString("MenuForSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1. Оплатить товар
        ///2. Изменить количество в каждой позиции
        ///3. Удалить товар из корзины
        ///
        ///Для выхода нажмите клавишу &apos;q&apos;
        ///
        ///Выберите действие:.
        /// </summary>
        internal static string MenuShowCart {
            get {
                return ResourceManager.GetString("MenuShowCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не авторизовались!.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль: .
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  рублей.
        /// </summary>
        internal static string RUB {
            get {
                return ResourceManager.GetString("RUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на К сожалению, оплата не прошла!.
        /// </summary>
        internal static string SuccessfulNotPayment {
            get {
                return ResourceManager.GetString("SuccessfulNotPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата прошла успешно!.
        /// </summary>
        internal static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для удаления введите ID товара: .
        /// </summary>
        internal static string ToDeleteEnterProductID {
            get {
                return ResourceManager.GetString("ToDeleteEnterProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для редактирования введите ID товара: .
        /// </summary>
        internal static string ToEditEnterProductID {
            get {
                return ResourceManager.GetString("ToEditEnterProductID", resourceCulture);
            }
        }
    }
}
